services:
  db:
    image: postgres:15-alpine
    container_name: streetcats-db
    restart: always
    environment:
      POSTGRES_DB: streetcats2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: streetcats-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_NAME=streetcats2
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=streetcatssecret123
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: